# Generated by Django 4.2 on 2023-04-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('capacidad', models.FloatField(verbose_name='Capacidad')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=255, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('mision', models.CharField(blank=True, max_length=255, verbose_name='Misión')),
                ('vision', models.CharField(blank=True, max_length=255, verbose_name='Visión')),
                ('telefono', models.CharField(blank=True, max_length=255, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Empresas',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EntidadEstatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscripcion', models.PositiveBigIntegerField(verbose_name='Número de Inscripción')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Entidad Estatal',
                'verbose_name_plural': 'Entidades Estatales',
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'verbose_name': 'Persona Natural',
                'verbose_name_plural': 'Personas Naturales',
            },
        ),
        migrations.CreateModel(
            name='Prefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.FloatField(verbose_name='Costo Total')),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario')),
                ('lugar_recogida', models.CharField(blank=True, max_length=255, verbose_name='Lugar de Recogida')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.almacen', verbose_name='Almacén')),
            ],
            options={
                'verbose_name': 'Prefactura',
                'verbose_name_plural': 'Prefacturas',
            },
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Semilla',
                'verbose_name_plural': 'Semillas',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_compra', models.CharField(max_length=255, verbose_name='Lugar de Compra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('cantidad_existente', models.IntegerField(verbose_name='Cantidad Existente')),
                ('cantidad_vendida', models.IntegerField(verbose_name='Cantidad Vendida')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.almacen', verbose_name='Almacén')),
                ('prefactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prefactura', verbose_name='Prefactura')),
                ('semilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.semilla')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='entidad_estatal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.entidadestatal', verbose_name='Entidad Estatal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona_natural',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.personanatural', verbose_name='Persona Natural'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa', verbose_name='Empresa'),
        ),
    ]
