# Generated by Django 4.2 on 2023-04-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='entidad_estatal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.entidadestatal', verbose_name='Entidad Estatal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='persona_natural',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.personanatural', verbose_name='Persona Natural'),
        ),
    ]
