# Generated by Django 4.2 on 2023-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_entidad_estatal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='main.producto'),
        ),
    ]
