# Generated by Django 4.2 on 2023-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_venta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='valor_total',
            field=models.FloatField(default=0, verbose_name='Valor total'),
        ),
    ]
