# Generated by Django 4.2 on 2023-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_venta_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cant_vendida',
            field=models.IntegerField(default=0, verbose_name='Cantidad Vendida'),
        ),
    ]
