# Generated by Django 4.2 on 2023-05-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_venta_cant_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 12, 4, 43, 575586, tzinfo=datetime.timezone.utc), verbose_name='Fecha'),
        ),
    ]
