# Generated by Django 4.2 on 2023-05-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default='django.utils.timezone.now', verbose_name='Fecha'),
        ),
    ]
