# Generated by Django 4.2 on 2023-05-07 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 12, 11, 49, 977295, tzinfo=datetime.timezone.utc), verbose_name='Fecha'),
        ),
    ]
