# Generated by Django 4.2 on 2023-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cliente_entidad_estatal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iamgen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
