# Generated by Django 4.2 on 2023-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_cliente_tipo_alter_prefactura_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefactura',
            name='producto',
            field=models.ManyToManyField(to='main.producto', verbose_name='Productos'),
        ),
    ]
