# Generated by Django 4.2 on 2023-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_prefactura_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Entidad Estatal', 'Entidad Estatal'), ('Persona Natural', 'Persona Natural')], default='Persona Natural', max_length=255),
        ),
        migrations.AlterField(
            model_name='prefactura',
            name='cantidad',
            field=models.FloatField(null=True, verbose_name='Cantidad a Comprar(Lb)'),
        ),
        migrations.AlterField(
            model_name='prefactura',
            name='costo_total',
            field=models.FloatField(verbose_name='Costo Total(MN)'),
        ),
        migrations.AlterField(
            model_name='prefactura',
            name='costo_unitario',
            field=models.FloatField(verbose_name='Costo Unitario(MN)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_existente',
            field=models.IntegerField(verbose_name='Cantidad Existente(Lb)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_vendida',
            field=models.IntegerField(verbose_name='Cantidad Vendida(Lb)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.FloatField(verbose_name='Valor(MN)'),
        ),
    ]
