# Generated by Django 4.2 on 2023-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_cliente_tipo_alter_prefactura_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefactura',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Entidad Estatal', 'Entidad Estatal')], default='Persona Natural', max_length=255),
        ),
    ]
