# Generated by Django 4.2 on 2023-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_prefactura_fecha_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Entidad Estatal', 'Entidad Estatal'), ('Persona Natural', 'Persona Natural')], default='Persona Natural', max_length=255),
        ),
    ]
