from main.signals.producto import delete_imagen_posdelete
from main.signals.prefactura import pre_delete_update_producto, pre_save_prefactura
from main.signals.venta import post_delete_update_venta_producto, post_save_update_venta_producto
