from .almacen import Almacenadmin
from .cliente import ClienteAdmin
from .empresa import EmpresaAdmin
from .entidad_estatal import EntidadEstatalAdmin
from .persona_natural import PersonaNaturalAdmin
from .prefactura import PrefacturaAdmin
from .producto import ProductoAdmin
from .venta import VentaAdmin
from .nomenclators import *
